language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - gcc-8
#    - libgtest-dev
    - cmake
#    - libopenblas-dev
    - libblas-dev
    - liblapack-dev
    - git
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libopencv-dev

before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
# dlib
- wget http://dlib.net/files/dlib-19.16.tar.bz2
- tar xf dlib-19.16.tar.bz2
- cd dlib-19.16
- mkdir build
- cd build
- cmake ..
- cmake --build . --config Release
- sudo make install
- sudo ldconfig
- cd "${TRAVIS_BUILD_DIR}"
# opencv
- git clone https://github.com/opencv/opencv.git
- cd opencv
- git checkout 3.4.3
- mkdir build && cd build
- cmake
  -DWITH_CUDA=OFF
  -DWITH_OPENCL=OFF
  -DWITH_FFMPEG=OFF
  -DBUILD_LIST=core,imgproc,imgcodecs
  -DBUILD_JAVA=OFF
  -DWITH_PROTOBUF=OFF
  -DBUILD_WEBP=OFF
  -DBUILD_opencv_python2=OFF
  -DBUILD_opencv_python3=OFF
  -DBUILD_opencv_apps=OFF
  -DBUILD_opencv_dnn=OFF
  -DWITH_IPP=OFF
  -DBUILD_PERF_TESTS=OFF
  -DBUILD_TESTS=OFF
  -DBUILD_SHARED_LIBS=OFF
  ..
#  -DBUILD_SHARED_LIBS=OFF
- cmake --build . --config Release
- sudo make install
- sudo ldconfig
- cd "${TRAVIS_BUILD_DIR}"
# gtest
#- cd /usr/src/gtest
#- sudo cmake .
#- sudo make
#- sudo cp *.a /usr/lib
#- cd "${TRAVIS_BUILD_DIR}"

script:
- cmake .
- cmake --build .
#- ctest -VV # run GTest
#- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u artbataev:$BINTRAY_API_KEY "https://api.bintray.com/content/artbataev1/Otus_Assignments/Otus_Cpp_15/$TRAVIS_BUILD_NUMBER/kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;publish=1"
  on:
    branch: master
